
default['openmrs']['webapp']['useradd'] = 'tomcat'
default['openmrs']['webapp']['groupadd'] = 'tomcat'
default['openmrs']['webapp']['remote_file_path'] = '/home/ubuntu/apache-tomcat-8.5.9.tar.gz'
default['openmrs']['webapp']['remote_file_location'] = 'http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.tar.gz'
default['openmrs']['webapp']['tomcatusersxml'] = '/opt/tomcat/conf/tomcat-users.xml'
default['openmrs']['webapp']['hostmanagercontext'] = '/opt/tomcat/webapps/host-manager/META-INF/context.xml'
default['openmrs']['webapp']['managercontext'] = '/opt/tomcat/webapps/manager/META-INF/context.xml'
default['openmrs']['webapp']['webxmlpath'] = '/opt/tomcat/webapps/manager/WEB-INF/web.xml'
default['openmrs']['webapp']['tomcatservicefile'] = '/etc/systemd/system/tomcat.service'
default['openmrs']['webapp']['tomcatextarctedpath'] = '/home/ubuntu/apache-tomcat-8.5.9'
default['openmrs']['webapp']['tomcatinsatlledpath'] = '/opt/tomcat/'

default['openmrs']['mysql']['admin_username'] = 'openmrs'
default['openmrs']['mysql']['admin_password'] = 'openmrs1234'
default['openmrs']['mysql']['root_username'] = 'root'
default['openmrs']['mysql']['root_password'] = 'openmrs1234'
default['openmrs']['mysql']['databasename'] = 'openmrs'
default['openmrs']['mysql']['host'] = '127.0.0.1'
default['openmrs']['mysql']['port'] = '3306'
default['openmrs']['mysql']['bind_address'] = '0.0.0.0'

default['openmrs']['openmrs']['openmrsfilepath'] = '/opt/tomcat/webapps/openmrs.war'
default['openmrs']['openmrs']['openmrssetuppath'] = '/var/lib/OpenMRS'
#default['openmrs']['webapp']['.openmrspathpermissions'] = '/home/ubuntu'
default['openmrs']['openmrs']['runtimepropertiesfilepath'] = '/var/lib/OpenMRS/openmrs-runtime.properties'
